spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
    password:
server:
  port: 8080
  servlet:
    context-path: /

---
spring:
  profiles: prd
server:
  port: 8081
  servlet:
    context-path: /
