spring:
  profiles:
    active:

---
spring:
  profiles: dev

server:
  port: 8080
  servlet:
    context-path: /dev

---
spring:
  profiles: prd
server:
  port: 8081
  servlet:
    context-path: /prd
